name: event_organizer
description: A Flutter application for event organizing

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  google_maps_flutter: ^2.5.0
  cached_network_image: ^3.3.0
  flutter_local_notifications: ^16.3.0
  intl: ^0.18.1
  url_launcher: ^6.2.2
  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  google_generative_ai: ^0.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true